### ISSUE TITLE
Working with Vite in the browser 浏览器下 vite 下运行 promise 报错

### ISSUE THREAD

**Issue by zhangchenna** [xuri/excelize-wasm#7] opened 2023-04-14 15:51 UTC

**Comment by xuri** [comment] 2023-04-15 06:22
Thanks for your feedback. Could you follow the issue template, and show us a complete, standalone example program or reproducible demo?

**Comment by zhangchenna** [comment] 2023-04-15 07:17
0086/#/home:1 Uncaught (in promise) incorrect header check
P

**Comment by zhangchenna** [comment] 2023-04-15 07:18
import { init } from 'excelize-wasm'

  onMounted(() => {
    init('./excelize.wasm.gz').then(excelize => {
      const f = excelize.NewFile();
      console.log(f);
    });
  });

**Comment by zhangchenna** [comment] 2023-04-15 07:47
<html>
<head>
  <meta charset="utf-8">
  <script src="https://zhangchenna-1252291207.cos.ap-beijing.myqcloud.com/index.js"></script>
</head>
<body>
  <div>
    <button onclick="download()">Download</button>
  </div>
  <script>
    console.log(excelizeWASM);
  function download() {
    excelizeWASM
      .init('https://zhangchenna-1252291207.cos.ap-beijing.myqcloud.com/excelize.wasm.gz')
      .then((excelize) => {
        const f = excelize.NewFile();
        // Create a new sheet.
        const { index } = f.NewSheet('Sheet2');
        // Set value of a cell.
        f.SetCellValue('Sheet2', 'A2', 'Hello world.');
        f.SetCellValue('Sheet1', 'B2', 100);
        // Set active sheet of the workbook.
        f.SetActiveSheet(index);
        // Save spreadsheet by the given path.
        const { buffer, error } = f.WriteToBuffer();
        if (error) {
          console.log(error);
          return;
        }
        const link = document.createElement('a');
        link.download = 'Book1.xlsx';
        link.href = URL.createObjectURL(
          new Blob([buffer], {
            type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
          })
        );
        link.click();
      });
    } 
  </script>
</body>

提示 Bad magic number

node 版本正常 浏览器运行报错

**Comment by zhangchenna** [comment] 2023-04-15 08:12
export async function init(wasmPath) {
  const go = new Go();
  let buffer;
  if (typeof window === 'undefined') {
    global.excelize = {};
  } else {
    window.excelize = {};
  }
  buffer = await (await fetch(wasmPath)).arrayBuffer();
  const result = await WebAssembly.instantiate(buffer, go.importObject);
  go.run(result.instance);
  return excelize;
}

把解压缩移除正常后浏览器就正常了 怀疑是那个pako 的问题

**Comment by xuri** [comment] 2023-04-15 09:04
Thanks for your feedback. This issue is caused by index.js in your code, please check your build configuration, this is out of the scope of this package. The following code works well:

```html
<html>
<head>
  <meta charset="utf-8">
  <script src="https://xuri.me/excelize-wasm/v0.0.3/index.js"></script>
</head>
<body>
  <div>
    <button onclick="download()">Download</button>
  </div>
  <script>
  function download() {
    excelizeWASM
      .init('https://zhangchenna-1252291207.cos.ap-beijing.myqcloud.com/excelize.wasm.gz')
      .then((excelize) => {
        const f = excelize.NewFile();
        // Save spreadsheet by the given path.
        const { buffer, error } = f.WriteToBuffer();
        if (error) {
          console.log(error);
          return;
        }
        const link = document.createElement('a');
        link.download = 'Book1.xlsx';
        link.href = URL.createObjectURL(
          new Blob([buffer], {
            type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
          })
        );
        link.click();
      });
    }
  </script>
</body>
```

**Comment by zhangchenna** [comment] 2023-04-15 09:17
所有代码都是来自你的 demo 我并没有修改

**Comment by xuri** [comment] 2023-04-15 09:43
Thanks for your feedback. I've tested and it works well. Please try with following code:

```html
<html>
<head>
  <meta charset="utf-8">
  <script src="https://xuri.me/excelize-wasm/v0.0.3/index.js"></script>
</head>
<body>
  <div>
    <button onclick="download()">Download</button>
  </div>
  <script>
  function download() {
    excelizeWASM
      .init('https://xuri.me/excelize-wasm/v0.0.3/excelize.wasm.gz')
      .then((excelize) => {
        const f = excelize.NewFile();
        // Create a new sheet.
        const { index } = f.NewSheet('Sheet2');
        // Set value of a cell.
        f.SetCellValue('Sheet2', 'A2', 'Hello world.');
        f.SetCellValue('Sheet1', 'B2', 100);
        // Set active sheet of the workbook.
        f.SetActiveSheet(index);
        // Save spreadsheet by the given path.
        const { buffer, error } = f.WriteToBuffer();
        if (error) {
          console.log(error);
          return;
        }
        const link = document.createElement('a');
        link.download = 'Book1.xlsx';
        link.href = URL.createObjectURL(
          new Blob([buffer], {
            type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
          })
        );
        link.click();
      });
    }
  </script>
</body>
```

**Comment by zhangchenna** [comment] 2023-04-16 14:21
> Thanks for your feedback. I've tested and it works well. Please try with following code:
> 
> ```
> <html>
> <head>
>   <meta charset="utf-8">
>   <script src="https://xuri.me/excelize-wasm/v0.0.3/index.js"></script>
> </head>
> <body>
>   <div>
>     <button onclick="download()">Download</button>
>   </div>
>   <script>
>   function download() {
>     excelizeWASM
>       .init('https://xuri.me/excelize-wasm/v0.0.3/excelize.wasm.gz')
>       .then((excelize) => {
>         const f = excelize.NewFile();
>         // Create a new sheet.
>         const { index } = f.NewSheet('Sheet2');
>         // Set value of a cell.
>         f.SetCellValue('Sheet2', 'A2', 'Hello world.');
>         f.SetCellValue('Sheet1', 'B2', 100);
>         // Set active sheet of the workbook.
>         f.SetActiveSheet(index);
>         // Save spreadsheet by the given path.
>         const { buffer, error } = f.WriteToBuffer();
>         if (error) {
>           console.log(error);
>           return;
>         }
>         const link = document.createElement('a');
>         link.download = 'Book1.xlsx';
>         link.href = URL.createObjectURL(
>           new Blob([buffer], {
>             type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
>           })
>         );
>         link.click();
>       });
>     }
>   </script>
> </body>
> ```
有没有关于单元格样式的demo 

 const style = f.NewStyle({
        Font: { Color: 'FFFFFF' },
        Fill: { Type: 'pattern', Color: ['E0EBF5'] },
      });

      console.log(style);

      f.SetColWidth('Sheet1', 'A', 'A', 50);
      f.SetColWidth('Sheet1', 'B', 'B', 30);
      f.SetRowStyle('Sheet1', 1, 1, style);
      f.SetCellStyle('Sheet1', 'A6', 'A6', style);

这么写不起做

**Comment by xuri** [comment] 2023-04-16 15:22
Please reference the docs of the [`SetCellStyle`](https://xuri.me/excelize/zh-hans/cell.html#SetCellStyle) function. Specify the `Pattern` field of the fill style.

**Comment by xuri** [comment] 2023-04-17 05:06
I'll close this issue, if you have any questions, please let me know to reopen this anytime.

**Closed by xuri** 2023-04-17 05:06 UTC

**Comment by dearmark** [comment] 2023-05-19 00:56
> export async function init(wasmPath) { const go = new Go(); let buffer; if (typeof window === 'undefined') { global.excelize = {}; } else { window.excelize = {}; } buffer = await (await fetch(wasmPath)).arrayBuffer(); const result = await WebAssembly.instantiate(buffer, go.importObject); go.run(result.instance); return excelize; }
> 
> 把解压缩移除正常后浏览器就正常了 怀疑是那个pako 的问题

Yes, it work. If you use Vite ,just add to `package.json`
```
"excelize-wasm": "github:dearmark/excelize-wasm",
```

**Comment by zhangchenna** [comment] 2023-05-19 01:31
> > export async function init(wasmPath) { const go = new Go(); let buffer; if (typeof window === 'undefined') { global.excelize = {}; } else { window.excelize = {}; } buffer = await (await fetch(wasmPath)).arrayBuffer(); const result = await WebAssembly.instantiate(buffer, go.importObject); go.run(result.instance); return excelize; }
> 
> > 
> 
> > 把解压缩移除正常后浏览器就正常了 怀疑是那个pako 的问题
> 
> 
> 
> Yes, it work. If someone use Vite and same problem ,just add to `package.json`
> 
> ```
> 
> "excelize-wasm": "github:dearmark/excelize-wasm",
> 
> ```

换了一个压缩控件就行，pako 自身的问题

**Comment by dearmark** [comment] 2023-05-19 21:31
> > > export async function init(wasmPath) { const go = new Go(); let buffer; if (typeof window === 'undefined') { global.excelize = {}; } else { window.excelize = {}; } buffer = await (await fetch(wasmPath)).arrayBuffer(); const result = await WebAssembly.instantiate(buffer, go.importObject); go.run(result.instance); return excelize; }
> > 
> > 
> > > 
> > 
> > 
> > > 把解压缩移除正常后浏览器就正常了 怀疑是那个pako 的问题
> > 
> > 
> > Yes, it work. If someone use Vite and same problem ,just add to `package.json`
> > ```
> > 
> > "excelize-wasm": "github:dearmark/excelize-wasm",
> > ```
> 
> 换了一个压缩控件就行，pako 自身的问题

实际上，在部署到nginx时，我代码需要调用的是`init('/wasm/excelize.wasm')`，因为nginx开启了gzip压缩，配合使用Vite生成dist时，会自动生成`excelize.wasm.gz`文件；在我的使用场景里，无需提前使用`.gz`文件，nginx自动映射。

**Comment by 657KB** [comment] 2025-01-17 23:33
This issue occurs because Vite's dev server decompresses resources by default, causing the blob passed to pako to be the decompressed content.
